plugins {
	id("org.gradle.toolchains.foojay-resolver-convention") version "0.9.0"
}

dependencyResolutionManagement {
	repositories {
		mavenCentral()
	}
	versionCatalogs {
		libs {
			//specifying version numbers, these go in the versionRef functions later
			version("gson", "2.11.0")

			//arg 1 is the library alias, 2 and 3 are its maven group and artifact
			//and the version is specified by the versionRef
			library("gson", "com.google.code.gson", "gson").versionRef("gson")

			//now you can refer to gson using `implementation libs.gson` and such
		}
	}
}

rootProject.name = "toybox"
include (
	"toybox-checksum",
	"toybox-gdiff",
	"toybox-manifest-index",
	"toybox-version-manifest",
)
